# -*- coding=UTF-8 -*-
# Code generated by scripts\python-version-updater.js, DO NOT EDIT
# fmt: off
"""
version info.
"""

from __future__ import absolute_import, division, print_function, unicode_literals

from datetime import datetime

VERSION = "3.6.4"
RELEASE_DATE = datetime.fromtimestamp(1632453394)
LAST_GIT_COMMIT_DESCRIBE = "v3.6.3-2-g06f988d"
LAST_GIT_COMMIT_HASH = "06f988dbbe771e761e70074f6fe64ef52e8b2a56"
LAST_GIT_COMMIT_AUTHOR_NAME = "NateScarlet"
LAST_GIT_COMMIT_AUTHOR_EMAIL = "NateScarlet@Gmail.com"
LAST_GIT_COMMIT_AUTHOR_DATE = datetime.fromtimestamp(1632453315)
LAST_GIT_COMMIT_SUBJECT = "chore: use generated version"
LAST_GIT_COMMIT_BODY = ""
